[package]
name = "endless-ecs"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = "0.4"
godot-bevy = "0.10"
bevy = { version = "0.17", default-features = false }
